# Generated by Django 4.2.4 on 2023-09-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("cat_id", models.AutoField(primary_key=True, serialize=False)),
                ("cat_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Components",
            fields=[
                ("comp_id", models.AutoField(primary_key=True, serialize=False)),
                ("cat", models.IntegerField()),
                ("comp_name", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.IntegerField()),
                ("comp_id", models.IntegerField()),
                ("amount_need", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Devices",
            fields=[
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("device_name", models.CharField(max_length=255)),
            ],
        ),
    ]
