# Generated by Django 4.2.4 on 2023-09-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_name", models.CharField(max_length=255)),
                ("in_stock", models.IntegerField()),
                ("amount_need", models.IntegerField()),
            ],
        ),
    ]
