# Generated by Django 4.2.4 on 2023-09-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0002_orderdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdata",
            name="cat",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
