# Generated by Django 4.2.4 on 2023-09-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0003_orderdata_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdata",
            name="cat",
            field=models.IntegerField(default=None, max_length=255),
        ),
    ]
