# Generated by Django 4.2.4 on 2023-09-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0005_alter_orderdata_cat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Replace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_name", models.CharField(max_length=255)),
                ("cat", models.IntegerField()),
            ],
        ),
    ]
