# Generated by Django 4.2.4 on 2023-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0006_replace"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdata",
            name="enough",
            field=models.BooleanField(default=True),
        ),
    ]
